# Generated by Django 3.0.6 on 2020-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_manager', '0002_expensedetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('health', 'Health')], max_length=50),
        ),
    ]
