# Generated by Django 3.0.6 on 2020-07-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_manager', '0003_auto_20200706_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='accounts',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expensedetails',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('socialLife', 'Social life'), ('education', 'Education'), ('household', 'Household'), ('transportaion', 'Transportaion'), ('fashion', 'Fashion'), ('health', 'Health'), ('selfDevelopment', 'Self development'), ('gift', 'Gift'), ('other', 'Other')], max_length=50),
        ),
    ]
