# Generated by Django 3.0.6 on 2020-07-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_manager', '0005_auto_20200706_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='accounts',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expensedetails',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Social Life', 'Social life'), ('Education', 'Education'), ('Household', 'Household'), ('Transportaion', 'Transportaion'), ('Fashion', 'Fashion'), ('Health', 'Health'), ('Self Development', 'Self development'), ('Gift', 'Gift'), ('Other', 'Other')], max_length=50),
        ),
    ]
