# Generated by Django 3.0.6 on 2020-07-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_manager', '0006_auto_20200707_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
