# Generated by Django 3.0.6 on 2020-07-16 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('e_manager', '0009_expensedetails_monthlyincome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensedetails',
            name='monthlyIncome',
        ),
        migrations.RemoveField(
            model_name='expensedetails',
            name='user',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlyIncome', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expensedetails',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_manager.Customer'),
        ),
    ]
